# Configuration for ATSM vehicle counting demo - cars4.mp4

video_path: "Media/cars4.mp4"
# mask_path: "Media/mask.png"  # Disabled for cars4.mp4
weights_path: "Weights/yolov8n.pt"

# Vehicle classes to count (must match YOLO class names)
classes_to_count: ["car", "truck", "motorbike", "bus"]
confidence_threshold: 0.6

# Counting line (x1, y1, x2, y2) - will need adjustment for cars4.mp4
count_line: [199, 363, 1208, 377]

# SORT tracker parameters
tracker:
  max_age: 20
  min_hits: 3
  iou_threshold: 0.3

# Signal timing logic
signal:
  car_count_threshold: 10
  normal_red_timer: 60
  reduced_red_timer: 30
  cooldown_duration: 10
  
# Category-specific thresholds (optional)
category_thresholds:
  car: 8
  truck: 3
  bus: 2
  motorbike: 5

# Size-based classification correction (in pixels)
size_thresholds:
  car: 
    min_area: 1000
    max_area: 50000
  bus: 
    min_area: 15000
    max_area: 100000
  truck: 
    min_area: 8000
    max_area: 80000
  motorbike: 
    min_area: 500
    max_area: 15000

